# Import the relevant libraries

In [1]:
import numpy as np

# Declaring scalars, vectors, and matrices

## Scalars

In [2]:
s = 5

In [3]:
s

5

## Vectors

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

## Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
s_array = np.array([5])

In [12]:
type(s_array)

numpy.ndarray

## Data shapes

In [13]:
m.shape

(2, 3)

In [14]:
v.shape

(3,)

In [15]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [16]:
s_array.shape

(1,)

## Creating a column vector

In [17]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [18]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [19]:
m+s

array([[10, 17, 11],
       [ 2,  5, 19]])

In [20]:
m+s_array

array([[10, 17, 11],
       [ 2,  5, 19]])

In [21]:
v+s

array([10,  3,  9])

In [22]:
v

array([ 5, -2,  4])

In [23]:
v+s_array

array([10,  3,  9])

In [24]:
m+v

array([[10, 10, 10],
       [ 2, -2, 18]])

## Addition

#### Task 1: Write below the code for adding the following matrices:

5,12,6
-3,0,14

9,8,7
1,3,-5

## Difference

#### Task 2: Write below the code for substracting the following matrices:

5,3
-2,4

7,-5
3,8

## Adding vectors together

#### Task 3: Write below the code for adding and substracting the following vectors:
{1,2,3,4,5} and {5,4,3,2,1} 

## Vector * Vector

In [ ]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [ ]:
np.dot(x,y)

In [ ]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [ ]:
np.dot(u,v)

## Scalar * Scalar

#### Task 4: Write the code below to calculate the dot product of the scalar values [10] and [-2]

## Scalar * Vector

In [ ]:
5*x

## Scalar * Matrix

####   Task 5: Write the code for the multiplication of [3] with matrix:

5,12,6
-3,0,14

## Matrix * Matrix

#### Task 6: Write the code for the multiplication of the previous matrix (task 5) with the following one:

[2,-1],[8,0],[3,0]]

## Transposing matrices

In [2]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [4]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [5]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [6]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [7]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

## Transposing scalars

In [8]:
s = np.array([5])

In [9]:
s.T

array([5])

## Transposing vectors

#### Task 6.1: Write the code below to transpore vector (1 2 3) and get it back to its original shape and format

### Addition of scalars

In [2]:
5 + 5

10

In [3]:
10 - 4

6

### Addition of matrices

In [4]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [5]:
m3 = np.array([[5,3],[-2,4]])
m3

array([[ 5,  3],
       [-2,  4]])

In [6]:
m1 + m3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

#### Task 7: Identify and fix the error above.

### Addition of vectors

In [7]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [8]:
v3 = np.array([1,2,3])
v3

array([1, 2, 3])

In [9]:
v1+v3

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

#### Task 8: Identify and fix the error above.

#### Task 9: Write the code below to increase every single element in hte folwooing matrix by 1:

5, 12,  6
-3,  0, 14

In [87]:
# create an 5x5 identiy matrix
I = np.eye(5)

# define a square matrix full rank
A = np.array([
    [1,4],
    [5,9]
])

# compute the inverse
A_inverse = np.linalg.inv(A)

In [88]:
A_inverse

array([[-0.81818182,  0.36363636],
       [ 0.45454545, -0.09090909]])

In [89]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [92]:
from numpy import linalg as LA

#### Task 10: Visit the NumPy API documentation for Liner Algebra as available by the URL
https://numpy.org/doc/stable/reference/routines.linalg.html 
#### Subsequently, write the code to calculate the eigen-value and eigen-vectors of the array A above.