<a href="https://colab.research.google.com/github/UjjwalJoshi1/datasciencetutorials/blob/main/Solving_systems_of_linear_equations_Your_tasks_Updated_2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import the relevant libraries

#### Visit the NumPy API documentation for Liner Algebra as available by the URL
https://numpy.org/doc/stable/reference/routines.linalg.html 


In [2]:
import numpy as np

#### Task 1: Write a program to resolve the following system of linear equations based on the calculation of an inverse matrix:
#### 2x-y+2z=10
#### x-2y+z=8
#### 3x-y+2z=11


In [12]:
A= np.array([[2,-1,2],[1,-2,1],[3,-1,2]])
A

array([[ 2, -1,  2],
       [ 1, -2,  1],
       [ 3, -1,  2]])

In [13]:
B=np.array([[10],[8],[11]])
B

array([[10],
       [ 8],
       [11]])

In [14]:
K = np.linalg.inv(A)
K

array([[-1.        ,  0.        ,  1.        ],
       [ 0.33333333, -0.66666667, -0.        ],
       [ 1.66666667, -0.33333333, -1.        ]])

In [15]:
np.dot(K,B)

array([[ 1.],
       [-2.],
       [ 3.]])

#### Task 2: Use the linalg.solve library and function to solve the system of 3 equations above in an alternative way (no need to calculate the inverse of the coefficients matrix m) 

In [16]:
np.linalg.solve(A,B)

array([[ 1.],
       [-2.],
       [ 3.]])

#### Task 3: Use the same linalg.solve library and function to solve a system of 4 equations by adding the following equation to the previous 3 ones. Adjust the previous system of equations in such a way that the problem can be resolved.

#### 3x-2y-z+4w=-3

In [17]:
L= np.array([[2,-1,2,0],[1,-2,1,0],[3,-1,2,0],[3,-2,-1,4]])
L

array([[ 2, -1,  2,  0],
       [ 1, -2,  1,  0],
       [ 3, -1,  2,  0],
       [ 3, -2, -1,  4]])

In [19]:
U=np.array([[10],[8],[11],[-3]])
U

array([[10],
       [ 8],
       [11],
       [-3]])

In [21]:
J=np.linalg.solve(L,U)
J

array([[ 1.  ],
       [-2.  ],
       [ 3.  ],
       [-1.75]])